cleanup:
  cronjobs: true
  jobs: true
ingress:
  domain: ""
acme:
  extraArgs: []
  extraEnv: {}
  files: []
  image:
    repository: ghcr.io/arikkfir/greenstar/acme
    tag: "local"
    pullPolicy: IfNotPresent
  rbac:
    annotations: {}
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
server:
  migrate:
    extraEnv: {}
    postgresPassword: ""
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  extraArgs: []
  extraEnv: {}
  image:
    repository: ghcr.io/arikkfir/greenstar/server
    tag: "local"
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  postgresPassword: ""
  rbac:
    annotations: {}
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  volumeMounts: []
  volumes: []
scrapers:
  image:
    repository: ghcr.io/arikkfir/greenstar/scrapers
    tag: "local"
    pullPolicy: IfNotPresent
  rbac:
    annotations: {}
ratesjob:
  extraEnv: {}
  image:
    repository: ghcr.io/arikkfir/greenstar/ratesjob
    tag: "local"
    pullPolicy: IfNotPresent
  rbac:
    annotations: {}
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  schedule: "0 * * * *"
frontend:
  extraArgs: []
  extraEnv: {}
  image:
    repository: ghcr.io/arikkfir/greenstar/frontend
    tag: "local"
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  rbac:
    annotations: {}
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "32Mi"
  volumeMounts: []
  volumes: []
  livenessProbe: true
  readinessProbe: true
  startupProbe: true
postgres:
  version: "17.2"
  clean: false
  extraArgs: []
  extraEnv: {}
  password: ""
  metrics: true
  ingress:
    enabled: false
  rbac:
    annotations: {}
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  volumes: []
  volumeMounts: []
