// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Tenant struct {
	ID          string `json:"id"`
	DisplayName string `json:"displayName"`
}

type TenantChanges struct {
	DisplayName string `json:"displayName"`
}
