// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

import { BaseAPIURL } from "../../services/util.ts"
import { useOperation, Method, Hook } from "../../util/operation.ts"

export interface Request {
    id: string
}
export type Response = {} | undefined

export function useDeleteTransaction(): Hook<Request, Response> {
    const opts = {
        initial: undefined,
        method: "DELETE" as Method,
        url: (req: Request) => `${BaseAPIURL}/transactions/${req.id}`,
    }
    return useOperation<Request, Response>(opts)
}
