# syntax=docker/dockerfile:1

### Build executable
FROM node:19.4 as builder
WORKDIR /workspace
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY public ./public
COPY src ./src
COPY tsconfig.json ./
EXPOSE 3000
ENTRYPOINT ["npm"]
CMD ["run", "start"]
