# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: greenstar
build:
  artifacts:
    - context: acme
      docker:
        buildArgs:
          VERSION: 0.0.0+local
        dockerfile: acme/Dockerfile
      image: ghcr.io/arikkfir/greenstar/acme
    - context: ratesjob
      docker:
        buildArgs:
          VERSION: 0.0.0+local
        dockerfile: ratesjob/Dockerfile
      image: ghcr.io/arikkfir/greenstar/ratesjob
    - context: server
      docker:
        buildArgs:
          VERSION: 0.0.0+local
        dockerfile: server/Dockerfile
        target: development
      image: ghcr.io/arikkfir/greenstar/server
      sync:
        manual:
          - src: src/**
            dest: /app/
    - context: frontend
      docker:
        buildArgs:
          VERSION: 0.0.0+local
        dockerfile: frontend/Dockerfile
        target: development
      image: ghcr.io/arikkfir/greenstar/frontend
      sync:
        manual:
          - src: public/**
            dest: /app/
          - src: src/**
            dest: /app/
          - src: index.html
            dest: /app/
  local:
    push: false
    useBuildkit: true
    concurrency: 5
deploy:
  helm:
    releases:
      - name: greenstar
        chartPath: ./deploy/chart
        packaged:
          appVersion: 0.0.0-{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        namespace: greenstar
        createNamespace: true
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - deploy/local/chart-local-values.yaml
          - hack/greenstar-frontend-values.yaml
          - hack/greenstar-server-values.yaml
          - hack/greenstar-tenants-values.yaml
        setValueTemplates:
          acme:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_acme}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_acme}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_acme}}"
          ratesjob:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_ratesjob}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_ratesjob}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_ratesjob}}"
          server:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_server}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_server}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_server}}"
          frontend:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_frontend}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_frontend}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_frontend}}"
