package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"

	"github.com/arikkfir/greenstar/backend/gql"
	"github.com/arikkfir/greenstar/backend/model"
)

// Tenants is the resolver for the tenants field.
func (r *queryResolver) Tenants(ctx context.Context) ([]*model.Tenant, error) {
	return r.TenantsService.Tenants(ctx)
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context, id string) (*model.Tenant, error) {
	return r.TenantsService.Tenant(ctx, id)
}

// Operation is the resolver for the operation field.
func (r *queryResolver) Operation(ctx context.Context, id string) (*model.Operation, error) {
	return r.OperationsService.Operation(ctx, id)
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
