package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"github.com/arik-kfir/greenstar/backend/gql"
	"github.com/arik-kfir/greenstar/backend/model"
)

// Tenants is the resolver for the tenants field.
func (r *queryResolver) Tenants(ctx context.Context) ([]*model.Tenant, error) {
	return r.TenantsService.Tenants(ctx)
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context, id string) (*model.Tenant, error) {
	return r.TenantsService.Tenant(ctx, id)
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, roots bool) ([]*model.Account, error) {
	return r.AccountsService.Accounts(ctx, roots)
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*model.Account, error) {
	return r.AccountsService.Account(ctx, id)
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context) ([]*model.Transaction, error) {
	return r.TransactionsService.Transactions(ctx)
}

// Operation is the resolver for the operation field.
func (r *queryResolver) Operation(ctx context.Context, id string) (*model.Operation, error) {
	return r.OperationsService.Operation(ctx, id)
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
