ingress:
  domain: greenstar.test

server:
  migrate:
    postgresPassword: local
  postgresPassword: local
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure
  extraEnv:
    OTEL_SDK_DISABLED:
      value: "true"

ratesjob:
  schedule: "0 * * * *"
  extraEnv:
    START_DATE_DURATION:
      value: P19M
    SUPPORTED_CURRENCIES:
      value: "USD,ILS,EUR"

frontend:
  extraArgs: [ "--", "--logLevel=info", "--port=3000", "--host=0.0.0.0" ]
  extraEnv:
    VITE_API_URL:
      value: https://api.greenstar.test
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  readinessProbe: false
  livenessProbe: false
  startupProbe: false

postgres:
  extraArgs:
    - -c
    - log_statement=all
  password: local
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      tlsSectionName: postgres
