// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

import { Account } from "../../models/account.ts"
import { DateProperties } from "../../models/account.ts"
import { BaseAPIURL } from "../../services/util.ts"
import { useOperation, Method, Hook } from "../../util/operation.ts"
import { QueryNilValue } from "../../services/util.ts"

export interface Request {
    id: string
    currency?: string
}
export type Response = Account | undefined

function buildURL(req: Request): string {
    const urlParams = new URLSearchParams()
    if (req.currency !== undefined) {
        if (req.currency === null) {
            urlParams.set("currency", QueryNilValue)
        } else {
            urlParams.set("currency", req.currency)
        }
    }

    return `${BaseAPIURL}/accounts/${req.id}${urlParams.size ? "?" + urlParams.toString() : ""}`
}

export function useGetAccount(): Hook<Request, Response> {
    const opts = {
        initial: undefined,
        method: "GET" as Method,
        url: buildURL,
        dateProperties: DateProperties,
    }
    return useOperation<Request, Response>(opts)
}
