// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

export interface Account {
    id: string
    createdAt: Date
    updatedAt: Date
    balance?: number
    displayName: string
    icon?: string
    parentID?: string
    totalIncomingAmount?: number
    totalOutgoingAmount?: number
}

export const DateProperties = ["createdAt", "updatedAt"]
