// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

export interface Tenant {
    id: string
    createdAt: Date
    updatedAt: Date
    displayName: string
}

export const DateProperties = ["createdAt", "updatedAt"]
