{
 "title": "GreenSTAR",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code) (rate(http_server_duration_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code) (rate(http_server_duration_sum[1m])) / sum by(http_method, http_status_code) (rate(http_server_duration_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PostgreSQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(datname) (pg_stat_database_numbackends)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Activities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(state) (pg_stat_activity_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}