// Code generated by greenstar scripts; DO NOT EDIT.

package transaction

import (
	"net/http"

	"github.com/arikkfir/greenstar/backend/internal/auth"
	"github.com/arikkfir/greenstar/backend/internal/server/util"
)

type GetRequest struct {
	TenantID string  `json:"-"`
	ID       string  `json:"id"`
	Currency *string `url:"currency,omitempty"`
}

func (lr *GetRequest) UnmarshalFromRequest(r *http.Request) error {
	lr.TenantID = r.PathValue("tenantID")
	if lr.TenantID == "" {
		return util.ErrBadRequest
	}
	lr.ID = r.PathValue("id")
	if lr.ID == "" {
		return util.ErrBadRequest
	}
	return nil
}

type GetResponse Transaction

func (s *Server) Get(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	l := util.Logger(ctx)
	if !auth.GetToken(ctx).IsPermittedForTenant(r.PathValue("tenantID"), "transactions:read") {
		util.ServeError(w, r, util.ErrForbidden)
		l.With("tenantID", r.PathValue("TenantPathVariableName")).WarnContext(ctx, "Access denied", "permission", "transactions:read")
		return
	}

	req := GetRequest{}
	if err := req.UnmarshalFromRequest(r); err != nil {
		util.ServeError(w, r, err)
		return
	}

	res, err := s.h.Get(ctx, req)
	if err != nil {
		if code := util.ServeError(w, r, err); code >= http.StatusInternalServerError {
			l.ErrorContext(ctx, "Failed getting transaction", "err", err)
		}
		return
	} else if res == nil {
		util.ServeError(w, r, util.ErrNotFound)
		return
	}

	if err := util.Marshal(w, r, http.StatusOK, res); err != nil {
		l.ErrorContext(ctx, "Failed marshaling transaction", "err", err)
		util.ServeError(w, r, err)
	}
}
