// Code generated by greenstar scripts; DO NOT EDIT.

package transaction

import "context"

type Handler interface {
	List(context.Context, ListRequest) (*ListResponse, error)
	Create(context.Context, CreateRequest) (*CreateResponse, error)
	Get(context.Context, GetRequest) (*GetResponse, error)
	Patch(context.Context, PatchRequest) (*PatchResponse, error)
	Update(context.Context, UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, DeleteRequest) error
	DeleteAll(context.Context, DeleteAllRequest) error
}
