// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"bytes"
	"context"
	"errors"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/arik-kfir/greenstar/backend/operations/model"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Mutation struct {
		Operation func(childComplexity int, id string, op model.OperationChanges) int
	}

	Operation struct {
		CreatedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		Name        func(childComplexity int) int
		Result      func(childComplexity int) int
		Status      func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	Query struct {
		Operation func(childComplexity int, id string) int
	}
}

type executableSchema struct {
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	return parsedSchema
}

func (e *executableSchema) Complexity(typeName, field string, childComplexity int, rawArgs map[string]interface{}) (int, bool) {
	ec := executionContext{nil, e}
	_ = ec
	switch typeName + "." + field {

	case "Mutation.operation":
		if e.complexity.Mutation.Operation == nil {
			break
		}

		args, err := ec.field_Mutation_operation_args(context.TODO(), rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.Operation(childComplexity, args["id"].(string), args["op"].(model.OperationChanges)), true

	case "Operation.createdAt":
		if e.complexity.Operation.CreatedAt == nil {
			break
		}

		return e.complexity.Operation.CreatedAt(childComplexity), true

	case "Operation.description":
		if e.complexity.Operation.Description == nil {
			break
		}

		return e.complexity.Operation.Description(childComplexity), true

	case "Operation.id":
		if e.complexity.Operation.ID == nil {
			break
		}

		return e.complexity.Operation.ID(childComplexity), true

	case "Operation.name":
		if e.complexity.Operation.Name == nil {
			break
		}

		return e.complexity.Operation.Name(childComplexity), true

	case "Operation.result":
		if e.complexity.Operation.Result == nil {
			break
		}

		return e.complexity.Operation.Result(childComplexity), true

	case "Operation.status":
		if e.complexity.Operation.Status == nil {
			break
		}

		return e.complexity.Operation.Status(childComplexity), true

	case "Operation.updatedAt":
		if e.complexity.Operation.UpdatedAt == nil {
			break
		}

		return e.complexity.Operation.UpdatedAt(childComplexity), true

	case "Query.operation":
		if e.complexity.Query.Operation == nil {
			break
		}

		args, err := ec.field_Query_operation_args(context.TODO(), rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Operation(childComplexity, args["id"].(string)), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	rc := graphql.GetOperationContext(ctx)
	ec := executionContext{rc, e}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputOperationChanges,
	)
	first := true

	switch rc.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Query(ctx, rc.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, rc.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(parsedSchema), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(parsedSchema, parsedSchema.Types[name]), nil
}

var sources = []*ast.Source{
	{Name: "../schema.graphqls", Input: `scalar DateTime

enum OperationStatus {
    PENDING
    ACCEPTED
    REJECTED
    STARTED
    COMPLETED
}

enum OperationResult {
    SUCCEEDED
    FAILED
}

type Operation {
    id: ID!
    name: String!
    description: String
    status: OperationStatus!
    result: OperationResult!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Query {
    operation(id: ID!): Operation
}

input OperationChanges {
    name: String!
    description: String
    status: OperationStatus!
    result: OperationResult!
}

type Mutation {
    operation(id: ID!, op: OperationChanges!): Operation!
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
