// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Account struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"displayName"`
	Labels      []*KeyAndValue `json:"labels"`
	Children    []*Account     `json:"children"`
	Parent      *Account       `json:"parent"`
}

type AccountUpdate struct {
	DisplayName *string             `json:"displayName"`
	Labels      []*KeyAndValueInput `json:"labels"`
	ParentID    *string             `json:"parentID"`
}

type KeyAndValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyAndValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type NewAccount struct {
	ID          *string             `json:"id"`
	DisplayName string              `json:"displayName"`
	Labels      []*KeyAndValueInput `json:"labels"`
	ParentID    *string             `json:"parentID"`
}

type NewTransaction struct {
	Date            time.Time `json:"Date"`
	TargetAccountID string    `json:"targetAccountID"`
	SourceAccountID string    `json:"sourceAccountID"`
	ReferenceID     string    `json:"referenceID"`
	Amount          Money     `json:"amount"`
	Description     string    `json:"description"`
}

type Tenant struct {
	ID          string `json:"id"`
	DisplayName string `json:"displayName"`
	Slug        string `json:"slug"`
}

type Transaction struct {
	ID            string    `json:"id"`
	Date          time.Time `json:"Date"`
	TargetAccount *Account  `json:"targetAccount"`
	SourceAccount *Account  `json:"sourceAccount"`
	ReferenceID   string    `json:"referenceID"`
	Amount        Money     `json:"amount"`
	Description   string    `json:"description"`
}
