// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

import { BaseAPIURL } from "../../services/util.ts"
import { Tenant } from "../../models/tenant.ts"
import { DateProperties } from "../../models/tenant.ts"
import { useOperation, Method, Hook } from "../../util/operation.ts"

export interface Request {
    id: string
    displayName: string
}
export type Response = Tenant | undefined

export function useUpdateTenant(): Hook<Request, Response> {
    const opts = {
        initial: undefined,
        method: "PUT" as Method,
        url: (req: Request) => `${BaseAPIURL}/tenants/${req.id}`,
        dateProperties: DateProperties,
    }
    return useOperation<Request, Response>(opts)
}
