// Code generated by greenstar scripts; DO NOT EDIT.

package account

import (
	"github.com/arikkfir/greenstar/backend/internal/auth"
	"github.com/arikkfir/greenstar/backend/internal/server/middleware"
	"github.com/arikkfir/greenstar/backend/internal/server/util"
	"net/http"
)

type DeleteRequest struct {
	ID string `json:"id"`
}

func (lr *DeleteRequest) UnmarshalFromRequest(r *http.Request) error {
	lr.ID = r.PathValue("id")
	if lr.ID == "" {
		return util.ErrBadRequest
	}
	return nil
}

type DeleteResponse struct{}

func (s *Server) Delete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	l := util.Logger(ctx)

	tenantID := middleware.GetTenantID(ctx)
	if tenantID != "" {
		l = l.With("tenantID", tenantID)
	}
	authToken := auth.GetToken(ctx)
	if !authToken.IsPermittedGlobally("accounts:delete") {
		if tenantID != "" {
			if !authToken.IsPermittedForTenant(tenantID, "accounts:delete") {
				util.ServeError(w, r, util.ErrForbidden)
				l.WarnContext(ctx, "Access denied", "permission", "accounts:delete")
				return
			}
		} else {
			util.ServeError(w, r, util.ErrForbidden)
			l.WarnContext(ctx, "Access denied", "permission", "accounts:delete")
			return
		}
	}

	req := DeleteRequest{}
	if err := req.UnmarshalFromRequest(r); err != nil {
		util.ServeError(w, r, err)
		return
	}

	err := s.h.Delete(ctx, req)
	if err != nil {
		if code := util.ServeError(w, r, err); code >= http.StatusInternalServerError {
			l.ErrorContext(ctx, "Failed deleting account", "err", err)
		}
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
