// Code generated by greenstar scripts; DO NOT EDIT.

package account

import (
	"time"

	"github.com/shopspring/decimal"
)

type Account struct {
	ID                  string           `json:"id"`
	CreatedAt           time.Time        `json:"createdAt"`
	UpdatedAt           time.Time        `json:"updatedAt"`
	Balance             *decimal.Decimal `json:"balance"`
	DisplayName         string           `json:"displayName"`
	Icon                *string          `json:"icon"`
	ParentID            *string          `json:"parentID"`
	TotalIncomingAmount *decimal.Decimal `json:"totalIncomingAmount"`
	TotalOutgoingAmount *decimal.Decimal `json:"totalOutgoingAmount"`
}
