// Code generated by greenstar scripts; DO NOT EDIT.

package account

import (
	"encoding/json"
	"net/http"
	"slices"

	"github.com/arikkfir/greenstar/backend/internal/auth"
	"github.com/arikkfir/greenstar/backend/internal/server/util"
	"github.com/shopspring/decimal"
)

type UpdateRequest struct {
	TenantID            string           `json:"-"`
	ID                  string           `json:"id"`
	Balance             *decimal.Decimal `json:"balance,omitempty"`
	DisplayName         string           `json:"displayName,omitempty"`
	Icon                *string          `json:"icon,omitempty"`
	ParentID            *string          `json:"parentID,omitempty"`
	TotalIncomingAmount *decimal.Decimal `json:"totalIncomingAmount,omitempty"`
	TotalOutgoingAmount *decimal.Decimal `json:"totalOutgoingAmount,omitempty"`
	properties          []string
}

func (lr *UpdateRequest) HasBalance() bool  { return slices.Contains(lr.properties, "balance") }
func (lr *UpdateRequest) HasIcon() bool     { return slices.Contains(lr.properties, "icon") }
func (lr *UpdateRequest) HasParentID() bool { return slices.Contains(lr.properties, "parentID") }
func (lr *UpdateRequest) HasTotalIncomingAmount() bool {
	return slices.Contains(lr.properties, "totalIncomingAmount")
}
func (lr *UpdateRequest) HasTotalOutgoingAmount() bool {
	return slices.Contains(lr.properties, "totalOutgoingAmount")
}
func (lr *UpdateRequest) UnmarshalJSON(data []byte) error {
	lr.properties = nil
	var tempMap map[string]json.RawMessage
	if err := json.Unmarshal(data, &tempMap); err != nil {
		return err
	}
	for key := range tempMap {
		lr.properties = append(lr.properties, key)
	}
	type typeAlias UpdateRequest
	alias := (*typeAlias)(lr)
	if err := json.Unmarshal(data, alias); err != nil {
		return err
	}
	return nil
}

type UpdateResponse Account

func (s *Server) Update(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	l := util.Logger(ctx)
	if !auth.GetToken(ctx).IsPermittedForTenant(r.PathValue("tenantID"), "accounts:update") {
		util.ServeError(w, r, util.ErrForbidden)
		l.With("tenantID", r.PathValue("TenantPathVariableName")).WarnContext(ctx, "Access denied", "permission", "accounts:update")
		return
	}

	req := UpdateRequest{}
	if err := util.UnmarshalBody(r, &req); err != nil {
		util.ServeError(w, r, err)
		return
	}
	req.TenantID = r.PathValue("tenantID")
	if req.TenantID == "" {
		util.ServeError(w, r, util.ErrBadRequest)
		return
	}
	req.ID = r.PathValue("id")
	if req.ID == "" {
		util.ServeError(w, r, util.ErrBadRequest)
		return
	}

	res, err := s.h.Update(ctx, req)
	if err != nil {
		if code := util.ServeError(w, r, err); code >= http.StatusInternalServerError {
			l.ErrorContext(ctx, "Failed updating account", "err", err)
		}
		return
	} else if res == nil {
		util.ServeError(w, r, util.ErrNotFound)
		return
	}

	if err := util.Marshal(w, r, http.StatusOK, res); err != nil {
		l.ErrorContext(ctx, "Failed marshaling account", "err", err)
		util.ServeError(w, r, err)
	}
}
