-- noinspection SpellCheckingInspectionForFile

CREATE TABLE currencies
(
    code           VARCHAR(5)   NOT NULL PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    symbol         VARCHAR(5)   NOT NULL,
    native_symbol  TEXT         NOT NULL,
    name           TEXT         NOT NULL,
    decimal_digits INT          NOT NULL,
    rounding       INT          NOT NULL,
    name_plural    TEXT         NOT NULL,
    type           TEXT         NOT NULL,
    country_codes  VARCHAR(2)[] NOT NULL
);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE currencies TO greenstar_server;

INSERT INTO currencies (code, symbol, native_symbol, name, decimal_digits, rounding, name_plural, type, country_codes)
VALUES ('AED', 'AED', 'د.إ', 'United Arab Emirates Dirham', 2, 0, 'UAE dirhams', 'fiat', '{AE}'),
       ('AFN', 'Af', '؋', 'Afghan Afghani', 0, 0, 'Afghan Afghanis', 'fiat', '{AF}'),
       ('ALL', 'ALL', 'Lek', 'Albanian Lek', 0, 0, 'Albanian lekë', 'fiat', '{AL}'),
       ('AMD', 'AMD', 'դր.', 'Armenian Dram', 0, 0, 'Armenian drams', 'fiat', '{AM}'),
       ('ANG', 'ƒ', 'NAƒ', 'NL Antillean Guilder', 2, 0, 'NL Antillean Guilders', 'fiat', '{CW,SX}'),
       ('AOA', 'Kz', 'Kz', 'Angolan Kwanza', 2, 0, 'Angolan Kwanza', 'fiat', '{AO}'),
       ('ARS', 'AR$', '$', 'Argentine Peso', 2, 0, 'Argentine pesos', 'fiat', '{AR}'),
       ('AUD', 'AU$', '$', 'Australian Dollar', 2, 0, 'Australian dollars', 'fiat', '{AU,CC,CX,HM,KI,NF,NR,TV}'),
       ('AWG', 'Afl.', 'Afl.', 'Aruban Florin', 2, 0, 'Aruban Florin', 'fiat', '{AW}'),
       ('AZN', 'man.', 'ман.', 'Azerbaijani Manat', 2, 0, 'Azerbaijani manats', 'fiat', '{AZ}'),
       ('BAM', 'KM', 'KM', 'Bosnia-Herzegovina Convertible Mark', 2, 0, 'Bosnia-Herzegovina convertible marks', 'fiat',
        '{BA}'),
       ('BBD', 'Bds$', '$', 'Barbadian Dollar', 2, 0, 'Barbadian Dollars', 'fiat', '{BB}'),
       ('BDT', 'Tk', '৳', 'Bangladeshi Taka', 2, 0, 'Bangladeshi takas', 'fiat', '{BD}'),
       ('BGN', 'BGN', 'лв.', 'Bulgarian Lev', 2, 0, 'Bulgarian leva', 'fiat', '{BG}'),
       ('BHD', 'BD', 'د.ب.‏', 'Bahraini Dinar', 3, 0, 'Bahraini dinars', 'fiat', '{BH}'),
       ('BIF', 'FBu', 'FBu', 'Burundian Franc', 0, 0, 'Burundian francs', 'fiat', '{BI}'),
       ('BMD', 'BD$', '$', 'Bermudan Dollar', 2, 0, 'Bermudan Dollars', 'fiat', '{BM}'),
       ('BND', 'BN$', '$', 'Brunei Dollar', 2, 0, 'Brunei dollars', 'fiat', '{BN}'),
       ('BOB', 'Bs', 'Bs', 'Bolivian Boliviano', 2, 0, 'Bolivian bolivianos', 'fiat', '{BO}'),
       ('BRL', 'R$', 'R$', 'Brazilian Real', 2, 0, 'Brazilian reals', 'fiat', '{BR}'),
       ('BSD', 'B$', '$', 'Bahamian Dollar', 2, 0, 'Bahamian Dollars', 'fiat', '{BS}'),
       ('BTN', 'Nu.', 'Nu.', 'Bhutanese Ngultrum', 2, 0, 'Bhutanese Ngultrum', 'fiat', '{BT}'),
       ('BWP', 'BWP', 'P', 'Botswanan Pula', 2, 0, 'Botswanan pulas', 'fiat', '{BW,ZW}'),
       ('BYN', 'Br', 'Br', 'Belarusian ruble', 2, 0, 'Belarusian rubles', 'fiat', '{}'),
       ('BYR', 'BYR', 'BYR', 'Belarusian Ruble', 0, 0, 'Belarusian rubles', 'fiat', '{BY}'),
       ('BZD', 'BZ$', '$', 'Belize Dollar', 2, 0, 'Belize dollars', 'fiat', '{BZ}'),
       ('CAD', 'CA$', '$', 'Canadian Dollar', 2, 0, 'Canadian dollars', 'fiat', '{CA}'),
       ('CDF', 'CDF', 'FrCD', 'Congolese Franc', 2, 0, 'Congolese francs', 'fiat', '{CD}'),
       ('CHF', 'CHF', 'CHF', 'Swiss Franc', 2, 0, 'Swiss francs', 'fiat', '{CH,LI}'),
       ('CLF', 'UF', 'UF', 'Unidad de Fomento', 2, 0, 'Unidad de Fomentos', 'fiat', '{CL}'),
       ('CLP', 'CL$', '$', 'Chilean Peso', 0, 0, 'Chilean pesos', 'fiat', '{CL}'),
       ('CNY', 'CN¥', 'CN¥', 'Chinese Yuan', 2, 0, 'Chinese yuan', 'fiat', '{CN}'),
       ('COP', 'CO$', '$', 'Coombian Peso', 0, 0, 'Colombian pesos', 'fiat', '{CO}'),
       ('CRC', '₡', '₡', 'Costa Rican Colón', 0, 0, 'Costa Rican colóns', 'fiat', '{CR}'),
       ('CUC', 'CUC$', '$', 'Cuban Convertible Peso', 2, 0, 'Cuban Convertible Peso', 'fiat', '{CU}'),
       ('CUP', '$MN', '$', 'Cuban Peso', 2, 0, 'Cuban Peso', 'fiat', '{CU}'),
       ('CVE', 'CV$', 'CV$', 'Cape Verdean Escudo', 2, 0, 'Cape Verdean escudos', 'fiat', '{CV}'),
       ('CZK', 'Kč', 'Kč', 'Czech Republic Koruna', 2, 0, 'Czech Republic korunas', 'fiat', '{CZ}'),
       ('DJF', 'Fdj', 'Fdj', 'Djiboutian Franc', 0, 0, 'Djiboutian francs', 'fiat', '{DJ}'),
       ('DKK', 'Dkr', 'kr', 'Danish Krone', 2, 0, 'Danish kroner', 'fiat', '{DK,FO,GL}'),
       ('DOP', 'RD$', 'RD$', 'Dominican Peso', 2, 0, 'Dominican pesos', 'fiat', '{DO}'),
       ('DZD', 'DA', 'د.ج.‏', 'Algerian Dinar', 2, 0, 'Algerian dinars', 'fiat', '{DZ}'),
       ('EGP', 'EGP', 'ج.م.‏', 'Egyptian Pound', 2, 0, 'Egyptian pounds', 'fiat', '{EG,PS}'),
       ('ERN', 'Nfk', 'Nfk', 'Eritrean Nakfa', 2, 0, 'Eritrean nakfas', 'fiat', '{ER}'),
       ('ETB', 'Br', 'Br', 'Ethiopian Birr', 2, 0, 'Ethiopian birrs', 'fiat', '{ET}'),
       ('EUR', '€', '€', 'Euro', 2, 0, 'Euros', 'fiat',
        '{AD,AT,AX,BE,BL,CP,CY,DE,EA,EE,ES,EU,FI,FR,FX,GF,GP,GR,IC,IE,IT,LT,LU,LV,MC,ME,MF,MQ,MT,NL,PM,PT,RE,SI,SK,SM,TF,VA,XK,YT,ZW}'),
       ('FJD', 'FJ$', '$', 'Fijian Dollar', 2, 0, 'Fijian Dollar', 'fiat', '{FJ}'),
       ('FKP', 'FK£', '£', 'Falkland Islands Pound', 2, 0, 'Falkland Islands Pound', 'fiat', '{FK}'),
       ('GBP', '£', '£', 'British Pound Sterling', 2, 0, 'British pounds sterling', 'fiat',
        '{GB,GG,GS,IM,JE,TA,UK,ZW}'),
       ('GEL', 'GEL', 'GEL', 'Georgian Lari', 2, 0, 'Georgian laris', 'fiat', '{GE}'),
       ('GGP', '£', '£', 'Guernsey pound', 2, 0, 'Guernsey pounds', 'fiat', '{}'),
       ('GHS', 'GH₵', 'GH₵', 'Ghanaian Cedi', 2, 0, 'Ghanaian cedis', 'fiat', '{GH}'),
       ('GIP', '£', '£', 'Gibraltar Pound', 2, 0, 'Gibraltar Pounds', 'fiat', '{GI}'),
       ('GMD', 'D', 'D', 'Gambian Dalasi', 2, 0, 'Gambian Dalasi', 'fiat', '{GM}'),
       ('GNF', 'FG', 'FG', 'Guinean Franc', 0, 0, 'Guinean francs', 'fiat', '{GN}'),
       ('GTQ', 'GTQ', 'Q', 'Guatemalan Quetzal', 2, 0, 'Guatemalan quetzals', 'fiat', '{GT}'),
       ('GYD', 'G$', '$', 'Guyanaese Dollar', 2, 0, 'Guyanaese Dollar', 'fiat', '{GY}'),
       ('HKD', 'HK$', '$', 'Hong Kong Dollar', 2, 0, 'Hong Kong dollars', 'fiat', '{HK}'),
       ('HNL', 'HNL', 'L', 'Honduran Lempira', 2, 0, 'Honduran lempiras', 'fiat', '{HN}'),
       ('HRK', 'kn', 'kn', 'Croatian Kuna', 2, 0, 'Croatian kunas', 'fiat', '{HR}'),
       ('HTG', 'G', 'G', 'Haitian Gourde', 2, 0, 'Haitian Gourde', 'fiat', '{HT}'),
       ('HUF', 'Ft', 'Ft', 'Hungarian Forint', 0, 0, 'Hungarian forints', 'fiat', '{HU}'),
       ('IDR', 'Rp', 'Rp', 'Indonesian Rupiah', 0, 0, 'Indonesian rupiahs', 'fiat', '{ID}'),
       ('ILS', '₪', '₪', 'Israeli New Sheqel', 2, 0, 'Israeli new sheqels', 'fiat', '{IL,PS}'),
       ('IMP', '£', '£', 'Manx pound', 2, 0, 'Manx pounds', 'fiat', '{}'),
       ('INR', 'Rs', 'টকা', 'Indian Rupee', 2, 0, 'Indian rupees', 'fiat', '{BT,IN}'),
       ('IQD', 'IQD', 'د.ع.‏', 'Iraqi Dinar', 0, 0, 'Iraqi dinars', 'fiat', '{IQ}'),
       ('IRR', 'IRR', '﷼', 'Iranian Rial', 0, 0, 'Iranian rials', 'fiat', '{IR}'),
       ('ISK', 'Ikr', 'kr', 'Icelandic Króna', 0, 0, 'Icelandic krónur', 'fiat', '{IS}'),
       ('JEP', '£', '£', 'Jersey pound', 2, 0, 'Jersey pound', 'fiat', '{}'),
       ('JMD', 'J$', '$', 'Jamaican Dollar', 2, 0, 'Jamaican dollars', 'fiat', '{JM}'),
       ('JOD', 'JD', 'د.أ.‏', 'Jordanian Dinar', 3, 0, 'Jordanian dinars', 'fiat', '{JO,PS}'),
       ('JPY', '¥', '￥', 'Japanese Yen', 0, 0, 'Japanese yen', 'fiat', '{JP}'),
       ('KES', 'Ksh', 'Ksh', 'Kenyan Shilling', 2, 0, 'Kenyan shillings', 'fiat', '{KE}'),
       ('KGS', 'KGS', 'KGS', 'Kyrgystani Som', 2, 0, 'Kyrgystani Som', 'fiat', '{KG}'),
       ('KHR', 'KHR', '៛', 'Cambodian Riel', 2, 0, 'Cambodian riels', 'fiat', '{KH}'),
       ('KMF', 'CF', 'FC', 'Comorian Franc', 0, 0, 'Comorian francs', 'fiat', '{KM}'),
       ('KPW', '₩', '₩', 'North Korean Won', 2, 0, 'North Korean Won', 'fiat', '{KP}'),
       ('KRW', '₩', '₩', 'South Korean Won', 0, 0, 'South Korean won', 'fiat', '{KR}'),
       ('KWD', 'KD', 'د.ك.‏', 'Kuwaiti Dinar', 3, 0, 'Kuwaiti dinars', 'fiat', '{KW}'),
       ('KYD', 'CI$', '$‏', 'Cayman Islands Dollar', 2, 0, 'Cayman Islands Dollar', 'fiat', '{KY}'),
       ('KZT', 'KZT', 'тңг.', 'Kazakhstani Tenge', 2, 0, 'Kazakhstani tenges', 'fiat', '{KZ}'),
       ('LAK', '₭N', '₭‏‏', 'Laotian Kip', 0, 0, 'Laotian Kip', 'fiat', '{LA}'),
       ('LBP', 'LB£', 'ل.ل.‏', 'Lebanese Pound', 0, 0, 'Lebanese pounds', 'fiat', '{LB}'),
       ('LKR', 'SLRs', 'SL Re', 'Sri Lankan Rupee', 2, 0, 'Sri Lankan rupees', 'fiat', '{LK}'),
       ('LRD', 'LD$', 'L$', 'Liberian Dollar', 2, 0, 'Liberian Dollar', 'fiat', '{LR}'),
       ('LSL', 'L', 'M', 'Lesotho Loti', 2, 0, 'Lesotho Loti', 'fiat', '{LS}'),
       ('LTL', 'Lt', 'Lt', 'Lithuanian Litas', 2, 0, 'Lithuanian litai', 'fiat', '{}'),
       ('LVL', 'Ls', 'Ls', 'Latvian Lats', 2, 0, 'Latvian lati', 'fiat', '{}'),
       ('LYD', 'LD', 'د.ل.‏', 'Libyan Dinar', 3, 0, 'Libyan dinars', 'fiat', '{LY}'),
       ('MAD', 'MAD', 'د.م.‏', 'Moroccan Dirham', 2, 0, 'Moroccan dirhams', 'fiat', '{EH,MA}'),
       ('MDL', 'MDL', 'MDL', 'Moldovan Leu', 2, 0, 'Moldovan lei', 'fiat', '{MD}'),
       ('MGA', 'MGA', 'MGA', 'Malagasy Ariary', 0, 0, 'Malagasy Ariaries', 'fiat', '{MG}'),
       ('MKD', 'MKD', 'MKD', 'Macedonian Denar', 2, 0, 'Macedonian denari', 'fiat', '{MK}'),
       ('MMK', 'MMK', 'K', 'Myanma Kyat', 0, 0, 'Myanma kyats', 'fiat', '{MM}'),
       ('MNT', '₮', '₮', 'Mongolian Tugrik', 2, 0, 'Mongolian Tugrik', 'fiat', '{MN}'),
       ('MOP', 'MOP$', 'MOP$', 'Macanese Pataca', 2, 0, 'Macanese patacas', 'fiat', '{MO}'),
       ('MRO', 'UM', 'UM', 'Mauritanian ouguiya', 2, 0, 'Mauritanian ouguiyas', 'fiat', '{MR}'),
       ('MUR', 'MURs', 'MURs', 'Mauritian Rupee', 0, 0, 'Mauritian rupees', 'fiat', '{MU}'),
       ('MVR', 'MRf', 'Rf', 'Maldivian Rufiyaa', 2, 0, 'Maldivian Rufiyaa', 'fiat', '{MV}'),
       ('MWK', 'MK', 'MK', 'Malawian Kwacha', 2, 0, 'Malawian Kwacha', 'fiat', '{MW}'),
       ('MXN', 'MX$', '$', 'Mexican Peso', 2, 0, 'Mexican pesos', 'fiat', '{MX}'),
       ('MYR', 'RM', 'RM', 'Malaysian Ringgit', 2, 0, 'Malaysian ringgits', 'fiat', '{MY}'),
       ('MZN', 'MTn', 'MTn', 'Mozambican Metical', 2, 0, 'Mozambican meticals', 'fiat', '{MZ}'),
       ('NAD', 'N$', 'N$', 'Namibian Dollar', 2, 0, 'Namibian dollars', 'fiat', '{NA}'),
       ('NGN', '₦', '₦', 'Nigerian Naira', 2, 0, 'Nigerian nairas', 'fiat', '{NG}'),
       ('NIO', 'C$', 'C$', 'Nicaraguan Córdoba', 2, 0, 'Nicaraguan córdobas', 'fiat', '{NI}'),
       ('NOK', 'Nkr', 'kr', 'Norwegian Krone', 2, 0, 'Norwegian kroner', 'fiat', '{BV,NO,SJ}'),
       ('NPR', 'NPRs', 'नेरू', 'Nepalese Rupee', 2, 0, 'Nepalese rupees', 'fiat', '{NP}'),
       ('NZD', 'NZ$', '$', 'New Zealand Dollar', 2, 0, 'New Zealand dollars', 'fiat', '{CK,NU,NZ,PN,TK}'),
       ('OMR', 'OMR', 'ر.ع.‏', 'Omani Rial', 3, 0, 'Omani rials', 'fiat', '{OM}'),
       ('PAB', 'B/.', 'B/.', 'Panamanian Balboa', 2, 0, 'Panamanian balboas', 'fiat', '{PA}'),
       ('PEN', 'S/.', 'S/.', 'Peruvian Nuevo Sol', 2, 0, 'Peruvian nuevos soles', 'fiat', '{PE}'),
       ('PGK', 'K', 'K', 'Papua New Guinean Kina', 2, 0, 'Papua New Guinean Kina', 'fiat', '{PG}'),
       ('PHP', '₱', '₱', 'Philippine Peso', 2, 0, 'Philippine pesos', 'fiat', '{PH}'),
       ('PKR', 'PKRs', '₨', 'Pakistani Rupee', 0, 0, 'Pakistani rupees', 'fiat', '{PK}'),
       ('PLN', 'zł', 'zł', 'Polish Zloty', 2, 0, 'Polish zlotys', 'fiat', '{PL}'),
       ('PYG', '₲', '₲', 'Paraguayan Guarani', 0, 0, 'Paraguayan guaranis', 'fiat', '{PY}'),
       ('QAR', 'QR', 'ر.ق.‏', 'Qatari Rial', 2, 0, 'Qatari rials', 'fiat', '{QA}'),
       ('RON', 'RON', 'RON', 'Romanian Leu', 2, 0, 'Romanian lei', 'fiat', '{RO}'),
       ('RSD', 'din.', 'дин.', 'Serbian Dinar', 0, 0, 'Serbian dinars', 'fiat', '{RS}'),
       ('RUB', 'RUB', 'руб.', 'Russian Ruble', 2, 0, 'Russian rubles', 'fiat', '{RU,SU}'),
       ('RWF', 'RWF', 'FR', 'Rwandan Franc', 0, 0, 'Rwandan francs', 'fiat', '{RW}'),
       ('SAR', 'SR', 'ر.س.‏', 'Saudi Riyal', 2, 0, 'Saudi riyals', 'fiat', '{SA}'),
       ('SBD', 'SI$', '$', 'Solomon Islands Dollar', 2, 0, 'Solomon Islands Dollars', 'fiat', '{SB}'),
       ('SCR', 'SRe', 'SR', 'Seychellois Rupee', 2, 0, 'Seychellois Rupees', 'fiat', '{SC}'),
       ('SDG', 'SDG', 'SDG', 'Sudanese Pound', 2, 0, 'Sudanese pounds', 'fiat', '{SD}'),
       ('SEK', 'Skr', 'kr', 'Swedish Krona', 2, 0, 'Swedish kronor', 'fiat', '{SE}'),
       ('SGD', 'S$', '$', 'Singapore Dollar', 2, 0, 'Singapore dollars', 'fiat', '{SG}'),
       ('SHP', '£', '£', 'Saint Helena Pound', 2, 0, 'Saint Helena Pounds', 'fiat', '{SH}'),
       ('SLL', 'Le', 'Le', 'Sierra Leonean Leone', 2, 0, 'Sierra Leonean Leone', 'fiat', '{SL}'),
       ('SOS', 'Ssh', 'Ssh', 'Somali Shilling', 0, 0, 'Somali shillings', 'fiat', '{SO}'),
       ('SRD', '$', '$', 'Surinamese Dollar', 2, 0, 'Surinamese Dollar', 'fiat', '{SR}'),
       ('STD', 'Db', 'Db', 'São Tomé and Príncipe dobra', 2, 0, 'São Tomé and Príncipe dobras', 'fiat', '{ST}'),
       ('SVC', '₡', '₡', 'Salvadoran Colón', 2, 0, 'Salvadoran Colón', 'fiat', '{}'),
       ('SYP', 'SY£', 'ل.س.‏', 'Syrian Pound', 0, 0, 'Syrian pounds', 'fiat', '{SY}'),
       ('SZL', 'L', 'E‏', 'Swazi Lilangeni', 2, 0, 'Swazi Lilangeni', 'fiat', '{SZ}'),
       ('THB', '฿', '฿', 'Thai Baht', 2, 0, 'Thai baht', 'fiat', '{TH}'),
       ('TJS', 'TJS', 'TJS', 'Tajikistani Somoni', 2, 0, 'Tajikistani Somoni', 'fiat', '{TJ}'),
       ('TMT', 'T', 'T‏', 'Turkmenistani Manat', 2, 0, 'Turkmenistani Manat', 'fiat', '{TM}'),
       ('TND', 'DT', 'د.ت.‏', 'Tunisian Dinar', 3, 0, 'Tunisian dinars', 'fiat', '{TN}'),
       ('TOP', 'T$', 'T$', 'Tongan Paʻanga', 2, 0, 'Tongan paʻanga', 'fiat', '{TO}'),
       ('TRY', 'TL', 'TL', 'Turkish Lira', 2, 0, 'Turkish Lira', 'fiat', '{TR}'),
       ('TTD', 'TT$', '$', 'Trinidad and Tobago Dollar', 2, 0, 'Trinidad and Tobago dollars', 'fiat', '{TT}'),
       ('TWD', 'NT$', 'NT$', 'New Taiwan Dollar', 2, 0, 'New Taiwan dollars', 'fiat', '{TW}'),
       ('TZS', 'TSh', 'TSh', 'Tanzanian Shilling', 0, 0, 'Tanzanian shillings', 'fiat', '{TZ}'),
       ('UAH', '₴', '₴', 'Ukrainian Hryvnia', 2, 0, 'Ukrainian hryvnias', 'fiat', '{UA}'),
       ('UGX', 'USh', 'USh', 'Ugandan Shilling', 0, 0, 'Ugandan shillings', 'fiat', '{UG}'),
       ('USD', '$', '$', 'US Dollar', 2, 0, 'US dollars', 'fiat',
        '{AC,AS,BQ,DG,EC,FM,GU,HT,IO,MH,MP,PA,PR,PW,SV,TC,TL,UM,US,VG,VI,ZW}'),
       ('UYU', '$U', '$', 'Uruguayan Peso', 2, 0, 'Uruguayan pesos', 'fiat', '{UY}'),
       ('UZS', 'UZS', 'UZS', 'Uzbekistan Som', 0, 0, 'Uzbekistan som', 'fiat', '{UZ}'),
       ('VEF', 'Bs.F.', 'Bs.F.', 'Venezuelan Bolívar', 2, 0, 'Venezuelan bolívars', 'fiat', '{VE}'),
       ('VND', '₫', '₫', 'Vietnamese Dong', 0, 0, 'Vietnamese dong', 'fiat', '{VN}'),
       ('VUV', 'VUV', 'VT', 'Vanuatu Vatu', 0, 0, 'Vanuatu Vatu', 'fiat', '{VU}'),
       ('WST', 'WS$', 'T', 'Samoan Tala', 2, 0, 'Samoan Tala', 'fiat', '{WS}'),
       ('XAF', 'FCFA', 'FCFA', 'CFA Franc BEAC', 0, 0, 'CFA francs BEAC', 'fiat', '{CF,CG,CM,GA,GQ,TD}'),
       ('XAG', 'XAG', 'XAG', 'Silver Ounce', 2, 0, 'Silver Ounces', 'metal', '{}'),
       ('XAU', 'XAU', 'XAU', 'Gold Ounce', 2, 0, 'Gold Ounces', 'metal', '{}'),
       ('XCD', 'EC$', '$', 'East Caribbean Dollar', 2, 0, 'East Caribbean Dollars', 'fiat',
        '{AG,AI,DM,GD,KN,LC,MS,VC}'),
       ('XDR', 'SDR', 'SDR', 'Special drawing rights', 2, 0, 'Special drawing rights', 'fiat', '{}'),
       ('XOF', 'CFA', 'CFA', 'CFA Franc BCEAO', 0, 0, 'CFA francs BCEAO', 'fiat', '{BF,BJ,CI,GW,ML,NE,SN,TG}'),
       ('XPF', 'CFP', 'CFP', 'CFP Franc', 0, 0, 'CFP francs', 'fiat', '{NC,PF,WF}'),
       ('YER', 'YR', 'ر.ي.‏', 'Yemeni Rial', 0, 0, 'Yemeni rials', 'fiat', '{YE}'),
       ('ZAR', 'R', 'R', 'South African Rand', 2, 0, 'South African rand', 'fiat', '{LS,NA,ZA,ZW}'),
       ('ZMK', 'ZK', 'ZK', 'Zambian Kwacha', 0, 0, 'Zambian kwachas', 'fiat', '{}'),
       ('ZMW', 'ZK', 'ZK', 'Zambian Kwacha', 0, 0, 'Zambian kwachas', 'fiat', '{ZM}'),
       ('ZWL', 'ZWL', '$', 'Zimbabwean dollar', 2, 0, 'Zimbabwean dollars', 'fiat', '{}'),
       ('XPT', 'XPT', 'XPT', 'Platinum Ounce', 6, 0, 'Platinum Ounces', 'metal', '{}'),
       ('XPD', 'XPD', 'XPD', 'Palladium Ounce', 6, 0, 'Palladium Ounces', 'metal', '{}'),
       ('BTC', '₿', '₿', 'Bitcoin', 8, 0, 'Bitcoins', 'crypto', '{}'),
       ('ETH', 'Ξ', 'Ξ', 'Ethereum', 18, 0, 'Ethereum', 'crypto', '{}'),
       ('BNB', 'BNB', 'BNB', 'Binance', 8, 0, 'Binance', 'crypto', '{}'),
       ('XRP', 'XRP', 'XRP', 'Ripple', 6, 0, 'Ripple', 'crypto', '{}'),
       ('SOL', 'SOL', 'SOL', 'Solana', 9, 0, 'Solana', 'crypto', '{}'),
       ('DOT', 'DOT', 'DOT', 'Polkadot', 10, 0, 'Polkadot', 'crypto', '{}'),
       ('AVAX', 'AVAX', 'AVAX', 'Avalanche', 18, 0, 'Avalanche', 'crypto', '{}'),
       ('MATIC', 'MATIC', 'MATIC', 'Matic Token', 18, 0, 'Matic Tokens', 'crypto', '{}'),
       ('LTC', 'Ł', 'Ł', 'Litecoin', 8, 0, 'Litecoins', 'crypto', '{}'),
       ('USDT', 'USDT', 'USDT', 'Tether', 2, 0, 'Tethers', 'crypto', '{}'),
       ('USDC', 'USDC', 'USDC', 'USD Coin', 2, 0, 'USD Coins', 'crypto', '{}'),
       ('DAI', 'DAI', 'DAI', 'Dai', 2, 0, 'Dais', 'crypto', '{}'),
       ('ARB', 'ARB', 'ARB', 'Arbitrum', 8, 0, 'Arbitrums', 'crypto', '{}'),
       ('OP', 'OP', 'OP', 'Optimism', 8, 0, 'Optimism', 'crypto', '{}'),
       ('VES', 'Bs.S.', 'Bs.S.', 'Venezuelan Bolívar', 2, 0, 'Venezuelan bolívars', 'fiat', '{}'),
       ('STN', 'STN', 'STN', 'São Tomé and Príncipe dobra', 2, 0, 'dobra', 'fiat', '{}'),
       ('MRU', 'MRU', 'MRU', 'Mauritanian ouguiya', 2, 0, 'ouguiya', 'fiat', '{}'),
       ('ZWG', 'ZWG', 'ZWG', 'Zimbabwe Gold', 2, 0, 'Zimbabwean gold', 'fiat', '{}'),
       ('SLE', 'SLE', 'SLE', 'Sierra Leonean leone', 2, 0, 'leone', 'fiat', '{}')